<a href="https://colab.research.google.com/github/lucasmontanheiro/colab/blob/main/Theory/Data_Science_03_Basic_Math_Statistics_02_Multiplying_matrices_and_basic_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Basic Math and Statistics

###Segment 2 - Multiplying matrices and basic linear algebra

In [2]:
import numpy as np
from numpy.random import randn

In [3]:
np.set_printoptions(precision=2)

**Multiplying matrices and basic linear algebra**

In [4]:
aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [7]:
bb = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [8]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [9]:
# first row and multiply by the first column
# and so on
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])